### PR TITLE
Adding endpoint options

### PR DESCRIPTION
**Pull request by yasserf**
@AlexBHarley

### CODE REVIEW

**Comment by AlexBHarley** [comment]
Looks good. Don't have write access though, so can't merge

**Comment by yasserf** [comment]
What about now?

**Comment by AlexBHarley** [comment]
Yep, good to go

**Comment by AlexBHarley** [comment]
Also think this repo is young enough that we don't need to keep branches

**Comment by yasserf** [comment]
Yup, we delete branches in general, just don't check straight into master :D

**Pull request merged**
