### PR TITLE
Being more friendly to swift

### PR DESCRIPTION
**Pull request by hexelon**
This should improve swift imports and interoperability

### CODE REVIEW

**Comment by yasserf** [comment]
Is there any change your tried this out? I know that flags tend to sometimes not work as well as one would hope!

**Comment by hexelon** [comment]
Agreed especially with the gradle plugin being deprecated :/ Anyway, I've recompiled the java 1.0.1 version for iOS with this flag and everything seems to be working (or at least the stuff I'm testing).

**Comment by yasserf** [comment]
That is good enough for me! Thanks for letting me know so quickly.

We are looking to get the library update to v2.0 pretty soon btw, the transpile works but were going to put in cleaner apis that use native json objects instead of the GSON equivalent from Java. 

I'm quite curious, is everything working okay so far with you? We tested all the APIs but I don't have a mac so never ran it myself personally.

**Comment by hexelon** [comment]
The apis a are working fine, I did run into some non deterministic connection status behavior which I've solved by using the listeners.

The current issue I'm facing is that sometimes getList or getRecord gets stuck, I'll open an issue once I can pinpoint when exactly this is happening.

My assumption is the that the await here, is never released for some reason - https://github.com/deepstreamIO/deepstream.io-client-java/blob/master/src/main/java/io/deepstream/RecordHandler.java#L80

**Pull request merged**
